
-- Delete tables if exist

DROP TABLE IF EXISTS date_table CASCADE;
DROP TABLE IF EXISTS time_table CASCADE;
DROP TABLE IF EXISTS error_table CASCADE;
DROP TABLE IF EXISTS log_import CASCADE;
DROP TABLE IF EXISTS timezone CASCADE;
DROP TABLE IF EXISTS location_table CASCADE;
DROP TABLE IF EXISTS measurement CASCADE;
DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS precipitation;
DROP TABLE IF EXISTS wind;
DROP TABLE IF EXISTS weather_code CASCADE;
DROP TABLE IF EXISTS weather;
